import clsx from 'clsx';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { Navbar } from '@/components/Navbar';
import { getAuthenticationState } from '@/lib/auth';

import './globals.css';
import { Providers } from './providers';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = async ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  const isAuthenticated = await getAuthenticationState();

  return (
    <html lang="en" className="dark">
      <head />
      <body
        className={clsx(
          'text-foreground bg-background min-h-screen antialiased',
          geistSans.variable,
          geistMono.variable
        )}
      >
        <Providers isAuthenticated={isAuthenticated}>
          <div className="relative flex h-screen flex-col font-sans">
            <Navbar />
            <main className="container mx-auto max-w-7xl grow px-6 pt-16 pb-10">{children}</main>
          </div>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
